config/routes.rb
Rails.application.routes.draw do
  get "tags/show"
  devise_for :users

  # Use devise_scope to ensure proper mapping for Devise routes
  devise_scope :user do
    root to: "devise/sessions#new"  # Redirect root to the sign-in page
  end

  get 'main/index', to: 'main#index'
 # root "main#index"

  match 'about', to: "main#about", via: :get

  resources :tasks
  resources :tags
  resources :categories
  
  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task Manager" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= stylesheet_link_tag "sessions", media: "all" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="container">
        <header>
          <div>
            <p>Welcome, <%= current_user.email %></p>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn" %>
          </div>
        </header>

        <nav>
          <ul>
            <li><%= link_to 'Dashboard', root_path %></li>
            <li><%= link_to 'Tasks', tasks_path %></li>
            <li><%= link_to 'Categories', categories_path %></li>
            <li><%= link_to 'Tags', tags_path %></li>
          </ul>
        </nav>

        <main>
          <%= yield %>
        </main>

        <aside>
            <h3 class="text-lg font-bold">Tags</h3>
            <ul class="list-disc pl-5">
              <% Tag.all.each do |tag| %>
                <li>
                  <%= link_to(tag.name, tasks_path(tag_id: tag.id), class: 'text-blue-500 underline') %>
                </li>
              <% end %>
            </ul>
          
        </aside>

        <footer>
            <p>&copy; <%= Time.current.year %> Task Manager. All rights reserved.</p>
            <div>
              <a href="https://facebook.com" target="_blank">Facebook</a>
              <a href="https://twitter.com" target="_blank">Twitter</a>
              <a href="https://instagram.com" target="_blank">Instagram</a>
            </div>
        </footer>
      </div>
    <% else %>
      <%= yield %> <!-- This will render the sign in/sign up pages -->
    <% end %>
  </body>
</html>